[2020-10-29 13:38:54,247] SEVERE {b7a.log.crash} - error("malformed URL: ") 
org.ballerinalang.jvm.util.exceptions.BallerinaException: error("malformed URL: ")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:564)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:287)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:106)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("malformed URL: ")
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:156)
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:141)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:561)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:65)
	at ballerina.http.1_0_0.client_endpoint.createSimpleHttpClient(client_endpoint.bal:314)
	at ballerina.http.1_0_0.$value$HttpClient.init(http_client.bal:38)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.$value$HttpClient.$init$(http_client.bal:25)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.http_client.createClient(http_client.bal:252)
	at ballerina.http.1_0_0.http_secure_client.createHttpSecureClient(http_secure_client.bal:275)
	at ballerina.http.1_0_0.$value$HttpCachingClient.init(caching/http_caching_client.bal:46)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.$value$HttpCachingClient.$init$(caching/http_caching_client.bal:29)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:277)
	at ballerina.http.1_0_0.client_endpoint.createDefaultClient(client_endpoint.bal:578)
	at ballerina.http.1_0_0.client_endpoint.createCookieClient(client_endpoint.bal:573)
	at ballerina.http.1_0_0.client_endpoint.checkForRetry(client_endpoint.bal:478)
	at ballerina.http.1_0_0.client_endpoint.initialize(client_endpoint.bal:448)
	at ballerina.http.1_0_0.$value$Client.init(client_endpoint.bal:57)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at ballerina.http.1_0_0.$value$Client.$init$(client_endpoint.bal:35)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.init(main.bal:16)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.$init$(main.bal:8)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__init_0(dbconnector:11)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__testinit_(dbconnector:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-10-29 13:54:35,319] SEVERE {b7a.log.crash} - error("malformed URL: ") 
org.ballerinalang.jvm.util.exceptions.BallerinaException: error("malformed URL: ")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:564)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:287)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:106)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("malformed URL: ")
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:156)
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:141)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:561)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:65)
	at ballerina.http.1_0_0.client_endpoint.createSimpleHttpClient(client_endpoint.bal:314)
	at ballerina.http.1_0_0.$value$HttpClient.init(http_client.bal:38)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.$value$HttpClient.$init$(http_client.bal:25)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.http_client.createClient(http_client.bal:252)
	at ballerina.http.1_0_0.http_secure_client.createHttpSecureClient(http_secure_client.bal:275)
	at ballerina.http.1_0_0.$value$HttpCachingClient.init(caching/http_caching_client.bal:46)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.$value$HttpCachingClient.$init$(caching/http_caching_client.bal:29)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:277)
	at ballerina.http.1_0_0.client_endpoint.createDefaultClient(client_endpoint.bal:578)
	at ballerina.http.1_0_0.client_endpoint.createCookieClient(client_endpoint.bal:573)
	at ballerina.http.1_0_0.client_endpoint.checkForRetry(client_endpoint.bal:478)
	at ballerina.http.1_0_0.client_endpoint.initialize(client_endpoint.bal:448)
	at ballerina.http.1_0_0.$value$Client.init(client_endpoint.bal:57)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at ballerina.http.1_0_0.$value$Client.$init$(client_endpoint.bal:35)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.init(main.bal:16)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.$init$(main.bal:8)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__init_0(dbconnector:11)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__testinit_(dbconnector:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-10-29 13:55:56,379] SEVERE {b7a.log.crash} - error("malformed URL: ") 
org.ballerinalang.jvm.util.exceptions.BallerinaException: error("malformed URL: ")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:564)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:287)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:106)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("malformed URL: ")
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:156)
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:141)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:561)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:65)
	at ballerina.http.1_0_0.client_endpoint.createSimpleHttpClient(client_endpoint.bal:314)
	at ballerina.http.1_0_0.$value$HttpClient.init(http_client.bal:38)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.$value$HttpClient.$init$(http_client.bal:25)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.http_client.createClient(http_client.bal:252)
	at ballerina.http.1_0_0.http_secure_client.createHttpSecureClient(http_secure_client.bal:275)
	at ballerina.http.1_0_0.$value$HttpCachingClient.init(caching/http_caching_client.bal:46)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.$value$HttpCachingClient.$init$(caching/http_caching_client.bal:29)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:277)
	at ballerina.http.1_0_0.client_endpoint.createDefaultClient(client_endpoint.bal:578)
	at ballerina.http.1_0_0.client_endpoint.createCookieClient(client_endpoint.bal:573)
	at ballerina.http.1_0_0.client_endpoint.checkForRetry(client_endpoint.bal:478)
	at ballerina.http.1_0_0.client_endpoint.initialize(client_endpoint.bal:448)
	at ballerina.http.1_0_0.$value$Client.init(client_endpoint.bal:57)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at ballerina.http.1_0_0.$value$Client.$init$(client_endpoint.bal:35)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.init(main.bal:16)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.$init$(main.bal:8)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__init_0(dbconnector:11)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__testinit_(dbconnector:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-10-29 13:56:49,990] SEVERE {b7a.log.crash} - error("malformed URL: ") 
org.ballerinalang.jvm.util.exceptions.BallerinaException: error("malformed URL: ")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:564)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:287)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:106)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("malformed URL: ")
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:156)
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:141)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:561)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:65)
	at ballerina.http.1_0_0.client_endpoint.createSimpleHttpClient(client_endpoint.bal:314)
	at ballerina.http.1_0_0.$value$HttpClient.init(http_client.bal:38)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.$value$HttpClient.$init$(http_client.bal:25)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.http_client.createClient(http_client.bal:252)
	at ballerina.http.1_0_0.http_secure_client.createHttpSecureClient(http_secure_client.bal:275)
	at ballerina.http.1_0_0.$value$HttpCachingClient.init(caching/http_caching_client.bal:46)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.$value$HttpCachingClient.$init$(caching/http_caching_client.bal:29)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:277)
	at ballerina.http.1_0_0.client_endpoint.createDefaultClient(client_endpoint.bal:578)
	at ballerina.http.1_0_0.client_endpoint.createCookieClient(client_endpoint.bal:573)
	at ballerina.http.1_0_0.client_endpoint.checkForRetry(client_endpoint.bal:478)
	at ballerina.http.1_0_0.client_endpoint.initialize(client_endpoint.bal:448)
	at ballerina.http.1_0_0.$value$Client.init(client_endpoint.bal:57)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at ballerina.http.1_0_0.$value$Client.$init$(client_endpoint.bal:35)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.init(main.bal:16)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.$init$(main.bal:8)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__init_0(dbconnector:11)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__testinit_(dbconnector:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-10-29 13:58:41,821] SEVERE {b7a.log.crash} - error("malformed URL: ") 
org.ballerinalang.jvm.util.exceptions.BallerinaException: error("malformed URL: ")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:564)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:287)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:106)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("malformed URL: ")
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:156)
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:141)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:561)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:65)
	at ballerina.http.1_0_0.client_endpoint.createSimpleHttpClient(client_endpoint.bal:314)
	at ballerina.http.1_0_0.$value$HttpClient.init(http_client.bal:38)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.$value$HttpClient.$init$(http_client.bal:25)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.http_client.createClient(http_client.bal:252)
	at ballerina.http.1_0_0.http_secure_client.createHttpSecureClient(http_secure_client.bal:275)
	at ballerina.http.1_0_0.$value$HttpCachingClient.init(caching/http_caching_client.bal:46)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.$value$HttpCachingClient.$init$(caching/http_caching_client.bal:29)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:277)
	at ballerina.http.1_0_0.client_endpoint.createDefaultClient(client_endpoint.bal:578)
	at ballerina.http.1_0_0.client_endpoint.createCookieClient(client_endpoint.bal:573)
	at ballerina.http.1_0_0.client_endpoint.checkForRetry(client_endpoint.bal:478)
	at ballerina.http.1_0_0.client_endpoint.initialize(client_endpoint.bal:448)
	at ballerina.http.1_0_0.$value$Client.init(client_endpoint.bal:57)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at ballerina.http.1_0_0.$value$Client.$init$(client_endpoint.bal:35)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.init(main.bal:16)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.$init$(main.bal:8)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__init_0(dbconnector:11)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__testinit_(dbconnector:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-10-29 14:00:23,150] SEVERE {b7a.log.crash} - error("malformed URL: ") 
org.ballerinalang.jvm.util.exceptions.BallerinaException: error("malformed URL: ")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:564)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:287)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:106)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("malformed URL: ")
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:156)
	at org.ballerinalang.jvm.api.BErrorCreator.createDistinctError(BErrorCreator.java:141)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:561)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:65)
	at ballerina.http.1_0_0.client_endpoint.createSimpleHttpClient(client_endpoint.bal:314)
	at ballerina.http.1_0_0.$value$HttpClient.init(http_client.bal:38)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.$value$HttpClient.$init$(http_client.bal:25)
	at ballerina.http.1_0_0.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_0.http_client.createClient(http_client.bal:252)
	at ballerina.http.1_0_0.http_secure_client.createHttpSecureClient(http_secure_client.bal:275)
	at ballerina.http.1_0_0.$value$HttpCachingClient.init(caching/http_caching_client.bal:46)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.$value$HttpCachingClient.$init$(caching/http_caching_client.bal:29)
	at ballerina.http.1_0_0.$value$HttpCachingClient.call(caching/http_caching_client.bal)
	at ballerina.http.1_0_0.caching.http_caching_client.createHttpCachingClient(caching/http_caching_client.bal:277)
	at ballerina.http.1_0_0.client_endpoint.createDefaultClient(client_endpoint.bal:578)
	at ballerina.http.1_0_0.client_endpoint.createCookieClient(client_endpoint.bal:573)
	at ballerina.http.1_0_0.client_endpoint.checkForRetry(client_endpoint.bal:478)
	at ballerina.http.1_0_0.client_endpoint.initialize(client_endpoint.bal:448)
	at ballerina.http.1_0_0.$value$Client.init(client_endpoint.bal:57)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at ballerina.http.1_0_0.$value$Client.$init$(client_endpoint.bal:35)
	at ballerina.http.1_0_0.$value$Client.call(client_endpoint.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.init(main.bal:16)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.$value$DBClient.$init$(main.bal:8)
	at sachini.dbconnector.0_1_0.$value$DBClient.call(main.bal)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__init_0(dbconnector:11)
	at sachini.dbconnector.0_1_0.dbconnector.$sachini_dbconnector_0_1_0__testinit_(dbconnector:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:500)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:276)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:244)
	at java.lang.Thread.run(Thread.java:748)
 
[2020-10-29 14:00:45,542] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:01:08,551] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:02:20,190] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:03:07,806] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:04:00,864] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:07:55,372] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:10:18,933] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:15:08,713] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:17:57,370] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:18:29,214] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-10-29 14:19:29,347] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:77)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
